name: random_word
description: Get random word in console
version: 1.0.0


environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
